
package org.example.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Convert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://example.org/", className = "org.example.proxy.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://example.org/", className = "org.example.proxy.ConvertResponse")
    @Action(input = "http://example.org/BankService/ConvertRequest", output = "http://example.org/BankService/ConvertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns org.example.proxy.Compte
     */
    @WebMethod(operationName = "GetAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAccount", targetNamespace = "http://example.org/", className = "org.example.proxy.GetAccount")
    @ResponseWrapper(localName = "GetAccountResponse", targetNamespace = "http://example.org/", className = "org.example.proxy.GetAccountResponse")
    @Action(input = "http://example.org/BankService/GetAccountRequest", output = "http://example.org/BankService/GetAccountResponse")
    public Compte getAccount(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.proxy.Compte>
     */
    @WebMethod(operationName = "GetAccounts")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAccounts", targetNamespace = "http://example.org/", className = "org.example.proxy.GetAccounts")
    @ResponseWrapper(localName = "GetAccountsResponse", targetNamespace = "http://example.org/", className = "org.example.proxy.GetAccountsResponse")
    @Action(input = "http://example.org/BankService/GetAccountsRequest", output = "http://example.org/BankService/GetAccountsResponse")
    public List<Compte> getAccounts();

}
